In [1]:
import numpy as np

def reconstruct_symmetric_matrix(relevant_part, size=12):
    """
    Reconstructs a symmetric matrix of given size from the relevant part.
    
    Parameters:
        relevant_part (array-like): A flattened array of the relevant part of the symmetric matrix.
        size (int): The size of the square matrix (default is 12).
        
    Returns:
        np.ndarray: The reconstructed symmetric matrix.
    """
    # Initialize an empty matrix
    matrix = np.zeros((size, size), dtype=int)
    
    # Fill the upper triangular part of the matrix with the relevant values
    indices = np.triu_indices(size)
    matrix[indices] = relevant_part
    
    # Mirror the upper triangular part to the lower triangular part
    matrix = matrix + matrix.T - np.diag(matrix.diagonal())
    
    return matrix

# Example usage:
# Define the relevant part (upper triangular including diagonal)
relevant_part = [
    0,1,1,0,1,0,0,0,0,0,0,0, # row 1
       0,0,1,0,1,0,0,0,0,0,0, # row 2
          0,1,1,0,1,0,0,0,0,0, # row 3
             0,0,1,0,1,0,0,0,0, # row 4
                0,1,1,0,1,0,0,0, # row 5
                   0,0,1,0,1,0,0, # row 6
                      0,1,1,0,1,0, # row 7
                         0,0,1,0,1, # row 8
                            0,1,1,0, # row 9
                               0,0,1, # row 10
                                  0,1, # row 11
                                     0  # row 12
]

# Reconstruct the full matrix
full_matrix = reconstruct_symmetric_matrix(relevant_part)

print(full_matrix)

[[0 1 1 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 1 0 0 0 0 0 0]
 [1 0 0 1 1 0 1 0 0 0 0 0]
 [0 1 1 0 0 1 0 1 0 0 0 0]
 [1 0 1 0 0 1 1 0 1 0 0 0]
 [0 1 0 1 1 0 0 1 0 1 0 0]
 [0 0 1 0 1 0 0 1 1 0 1 0]
 [0 0 0 1 0 1 1 0 0 1 0 1]
 [0 0 0 0 1 0 1 0 0 1 1 0]
 [0 0 0 0 0 1 0 1 1 0 0 1]
 [0 0 0 0 0 0 1 0 1 0 0 1]
 [0 0 0 0 0 0 0 1 0 1 1 0]]


In [5]:
import numpy as np

def reconstruct_symmetric_matrix_no_diag(relevant_part, size=12):
    """
    Reconstructs a symmetric matrix of given size from the relevant part, excluding the diagonal.
    
    Parameters:
        relevant_part (array-like): A flattened array of the strictly upper triangular part of the symmetric matrix.
        size (int): The size of the square matrix (default is 12).
        
    Returns:
        np.ndarray: The reconstructed symmetric matrix with diagonal values set to 0.
    """
    # Initialize an empty matrix
    matrix = np.zeros((size, size), dtype=float)
    
    # Fill the strictly upper triangular part of the matrix
    indices = np.triu_indices(size, k=1)  # k=1 excludes the diagonal
    matrix[indices] = relevant_part
    
    # Mirror the strictly upper triangular part to the lower triangular part
    matrix = matrix + matrix.T
    
    return matrix

# Example usage:
# Define the relevant part (strictly upper triangular, excluding diagonal)
# relevant_part = [
#     1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, # row 1
#        0, 1, 0, 1, 0, 0, 0, 0, 0, 0, # row 2
#           1, 1, 0, 1, 0, 0, 0, 0, 0, # row 3
#              0, 1, 0, 1, 0, 0, 0, 0, # row 4
#                 1, 1, 0, 1, 0, 0, 0, # row 5
#                    0, 1, 0, 1, 0, 0, # row 6
#                       1, 1, 0, 1, 0, # row 7
#                          0, 1, 0, 1, # row 8
#                             1, 1, 0, # row 9
#                                0, 1, # row 10
#                                   1  # row 11
# ]
relevant_part = np.linspace(0,1,66)

# Reconstruct the full matrix
full_matrix = reconstruct_symmetric_matrix_no_diag(relevant_part)

print(full_matrix)

def extract_relevant_part(matrix):
    """
    Extracts the relevant part (strictly upper triangular values, excluding the diagonal) 
    from a symmetric matrix.
    
    Parameters:
        matrix (np.ndarray): A square symmetric matrix (e.g., 12x12).
        
    Returns:
        np.ndarray: A 1D array containing the strictly upper triangular values.
    """
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Input must be a square matrix.")
    
    # Extract strictly upper triangular values
    relevant_part = matrix[np.triu_indices(matrix.shape[0], k=1)]
    return relevant_part

new_relevant_part = extract_relevant_part(full_matrix)

print(new_relevant_part)
assert np.array_equal(relevant_part, new_relevant_part)
print(len(relevant_part))

[[0.         0.         0.01538462 0.03076923 0.04615385 0.06153846
  0.07692308 0.09230769 0.10769231 0.12307692 0.13846154 0.15384615]
 [0.         0.         0.16923077 0.18461538 0.2        0.21538462
  0.23076923 0.24615385 0.26153846 0.27692308 0.29230769 0.30769231]
 [0.01538462 0.16923077 0.         0.32307692 0.33846154 0.35384615
  0.36923077 0.38461538 0.4        0.41538462 0.43076923 0.44615385]
 [0.03076923 0.18461538 0.32307692 0.         0.46153846 0.47692308
  0.49230769 0.50769231 0.52307692 0.53846154 0.55384615 0.56923077]
 [0.04615385 0.2        0.33846154 0.46153846 0.         0.58461538
  0.6        0.61538462 0.63076923 0.64615385 0.66153846 0.67692308]
 [0.06153846 0.21538462 0.35384615 0.47692308 0.58461538 0.
  0.69230769 0.70769231 0.72307692 0.73846154 0.75384615 0.76923077]
 [0.07692308 0.23076923 0.36923077 0.49230769 0.6        0.69230769
  0.         0.78461538 0.8        0.81538462 0.83076923 0.84615385]
 [0.09230769 0.24615385 0.38461538 0.50769231 0.6