# Fronzen Lake

Gymnasium: https://gymnasium.farama.org/index.html
FronzenLake: https://gymnasium.farama.org/environments/toy_text/frozen_lake/

In [8]:
# imports

import gymnasium as gym
import numpy as np
import random
import tqdm
from tqdm.notebook import tqdm
import time

In [5]:
# Evironement

env = gym.make("FrozenLake-v1", map_name="8x8", render_mode='None' is_slippery=False)
print(env.observation_space)
print(env.observation_space.n)
print(env.observation_space.sample())
print(env.action_space)
print(env.action_space.n)
print(env.action_space.sample())

state, info = env.reset()
print(state)
print(info)


Discrete(64)
64
53
Discrete(4)
4
1
0
{'prob': 1}


In [7]:
# Example
# Initialise the environment
#env = gym.make("FrozenLake-v1", render_mode="human")

# Reset the environment to generate the first observation
observation, info = env.reset(seed=42)
for _ in range(1000):
    # this is where you would insert your policy
    action = env.action_space.sample()

    # step (transition) through the environment with the action
    # receiving the next observation, reward and if the episode has terminated or truncated
    observation, reward, terminated, truncated, info = env.step(action)


    # If the episode has ended then we can reset to start a new episode
    if terminated or truncated:
        observation, info = env.reset()

env.close()


KeyboardInterrupt: 

: 

In [7]:
# initialize Q table
Qtable = np.zeros((env.observation_space.n, env.action_space.n))
print(Qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# train

render_ep = 1000

n_training_episodes = 10000
learning_rate = 0.7

max_steps = 99
gamma = 0.95

max_epsilon = 1.0
min_epsilon = 0.05
decay_rate = 0.0005

for episode in tqdm(range(n_training_episodes)):
    if episode % render_ep == 0:  # For every 10th episode, render as human
        env = gym.make("FrozenLake-v1", map_name="8x8", render_mode="human", is_slippery=False)
    else:
        env = gym.make("FrozenLake-v1", map_name="8x8", render_mode="None", is_slippery=False)

    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    
    state, info = env.reset()

    for step in range(max_steps):

        random_num = random.uniform(0,1)
        if(random_num > epsilon):
            action = np.argmax(Qtable[state][:])
        else:
            action = env.action_space.sample()

        new_state, reward, terminated, truncated, info = env.step(action)
        #if(reward > 0):
         #   print("Reward")

        Qtable[state][action] = Qtable[state][action] + learning_rate * (reward + gamma * np.max(Qtable[new_state]) - Qtable[state][action])

        if terminated or truncated:
            break

        state = new_state
        

  0%|          | 0/10000 [00:00<?, ?it/s]

KeyboardInterrupt: 

: 

In [26]:
print(Qtable)

[[0.73509189 0.77378094 0.77378094 0.73509189]
 [0.73509189 0.         0.81450625 0.77378094]
 [0.77378094 0.857375   0.77378094 0.81450625]
 [0.81450625 0.         0.77378094 0.77378094]
 [0.77378094 0.81450625 0.         0.73509189]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.         0.81450625]
 [0.         0.         0.         0.        ]
 [0.81450625 0.         0.857375   0.77378094]
 [0.81450625 0.9025     0.9025     0.        ]
 [0.857375   0.95       0.         0.857375  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.95       0.857375  ]
 [0.9025     0.95       1.         0.9025    ]
 [0.         0.         0.         0.        ]]


In [28]:
# Evaluate

n_eval_episodes = 100

episode_rewards = []


for episode in tqdm(range(n_eval_episodes)):
    state, info = env.reset()

    step = 0
    total_rewards_ep = 0

    for step in range(max_steps):

        action = np.argmax(Qtable[state][:])

        new_state, reward, terminated, truncated, info = env.step(action)

        total_rewards_ep += reward

        if terminated or truncated:
            break

        state = new_state

    episode_rewards.append(total_rewards_ep)

mean_reward = np.mean(episode_rewards)
std_reward = np.std(episode_rewards)

print(f"mean reward {mean_reward}")
print(f"std reward {std_reward}")

  0%|          | 0/100 [00:00<?, ?it/s]

mean reward 1.0
std reward 0.0


In [34]:
env = gym.make("FrozenLake-v1", map_name="4x4", render_mode="human", is_slippery=False)

n_render_episodes = 10


for episode in tqdm(range(n_render_episodes)):
    state, info = env.reset()

    step = 0

    for step in range(max_steps):

        action = np.argmax(Qtable[state][:])

        new_state, reward, terminated, truncated, info = env.step(action)
        #env.render()

        if terminated or truncated:
            break

        state = new_state

  0%|          | 0/10 [00:00<?, ?it/s]